workflows:
  build-android:
    name: Build Android APK
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build unsigned release APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
